Repository mingxoxo/cub3d, pull requests merged in 2023-03, with the labels that each got.

#4 feat : #3/Check map error
  Makefile
  cub3d.h
  ft_func/math.c
  main.c
  parsing/check_map.c
  parsing/ds_queue.c
  parsing/parse_map.c
Labels: 💻 feat, 🤖 norm

#8 feat : #6/Parsing element
  Makefile
  cub3d.h
  ft_func/memory.c
  init.c
  main.c
  maps/total.cub
  parsing/check_map.c
  parsing/parse.c
  parsing/parse_info.c
  parsing/parse_map.c
Labels: 📄 docs, 💻 feat, 🛠 refactor, 🐞 fix

#12 feat : #10/Add color rgb parsing
  Makefile
  cub3d.h
  init.c
  maps/ex.cub
  maps/ex2.cub
  maps/ex3.cub
  maps/ex4.cub
  parsing/check_map.c
  parsing/parse.c
  parsing/parse_color.c
  parsing/parse_info.c
Labels: 📄 docs, 💻 feat, 🤖 norm, 🐞 fix

#13 feat : #9/Check the path to the texture file
  Makefile
  cub3d.h
  ft_func/memory.c
  init.c
  key_press.c
  main.c
  maps/ex.cub
  mlx_opengl/Makefile
  mlx_opengl/font.c
  mlx_opengl/font.xcf
  mlx_opengl/mlx.h
  mlx_opengl/mlx_init_loop.m
  mlx_opengl/mlx_int.h
  mlx_opengl/mlx_int_str_to_wordtab.c
  mlx_opengl/mlx_mouse.m
  mlx_opengl/mlx_new_image.m
  mlx_opengl/mlx_new_window.h
  mlx_opengl/mlx_new_window.m
  mlx_opengl/mlx_opengl.h
  mlx_opengl/mlx_opengl.m
  mlx_opengl/mlx_png.c
  mlx_opengl/mlx_png.h
  mlx_opengl/mlx_rgb.c
  mlx_opengl/mlx_shaders.c
  mlx_opengl/mlx_xpm.c
  parsing/get_image.c
  parsing/parse.c
  textures/ea.xpm
  textures/no.xpm
  textures/so.xpm
  textures/we.xpm
Labels: 📄 docs, 💻 feat

#15 feat : #14/Modify player information initialization
  cub3d.h
  init.c
  parsing/parse.c
  parsing/parse_color.c
  parsing/parse_info.c
  parsing/parse_map.c
Labels: 💻 feat, 🛠 refactor

#16 feat : #7/Implement raycaster
  Makefile
  cub3d.h
  ft_func/memory.c
  init.c
  key_press.c
  main.c
  maps/ex.cub
  maps/ex2.cub
  parsing/get_image.c
  render/init.c
  render/render.c
  render/screen.c
Labels: 💻 feat

#19 feat : #17/Refactor raycast part
  Makefile
  cub3d.h
  init.c
  key_press.c
  main.c
  render/core.c
  render/render.c
Labels: 💻 feat, 🤖 norm, 🛠 refactor, 🐞 fix

#21 feat: #20/Add bonus directory
  Makefile
  bonus/cub3d_bonus.h
  bonus/ft_func/error_exit_bonus.c
  bonus/ft_func/file_bonus.c
  bonus/ft_func/lst_bonus.c
  bonus/ft_func/math_bonus.c
  bonus/ft_func/memory_bonus.c
  bonus/init_bonus.c
  bonus/key_press_bonus.c
  bonus/main_bonus.c
  bonus/parsing/check_map_bonus.c
  bonus/parsing/ds_queue_bonus.c
  bonus/parsing/get_image_bonus.c
  bonus/parsing/parse_bonus.c
  bonus/parsing/parse_color_bonus.c
  bonus/parsing/parse_info_bonus.c
  bonus/parsing/parse_map_bonus.c
  bonus/render/core_bonus.c
  bonus/render/init_bonus.c
  bonus/render/render_bonus.c
  bonus/render/screen_bonus.c
  mandatory/cub3d.h
  mandatory/ft_func/error_exit.c
  mandatory/ft_func/file.c
  mandatory/ft_func/lst.c
  mandatory/ft_func/math.c
  mandatory/ft_func/memory.c
  mandatory/init.c
  mandatory/key_press.c
  mandatory/main.c
  mandatory/parsing/check_map.c
  mandatory/parsing/ds_queue.c
  mandatory/parsing/get_image.c
  mandatory/parsing/parse.c
  mandatory/parsing/parse_color.c
  mandatory/parsing/parse_info.c
  mandatory/parsing/parse_map.c
  mandatory/render/core.c
  mandatory/render/init.c
  mandatory/render/render.c
  mandatory/render/screen.c
Labels: 📄 docs, 💻 feat, 🤖 norm, 🐞 fix, 💡 bonus

#24 feat : #18/Minimap system
  Makefile
  bonus/cub3d_bonus.h
  bonus/minimap_bonus.c
  bonus/render/render_bonus.c
  mandatory/cub3d.h
  mandatory/render/render.c
  maps/ex3.cub
Labels: 💻 feat, 💡 bonus

#26 feat : #25/Parse door and animated sprite info
  Makefile
  bonus/cub3d_bonus.h
  bonus/ft_func/memory_bonus.c
  bonus/init_bonus.c
  bonus/parsing/check_map_bonus.c
  bonus/parsing/divide_lst_type_bonus.c
  bonus/parsing/door_sprite_bonus.c
  bonus/parsing/get_image_bonus.c
  bonus/parsing/parse_bonus.c
  mandatory/parsing/get_image.c
  maps/ex4.cub
  textures/exit.xpm
  textures/hero.xpm
  textures/hero2.xpm
Labels: 💻 feat, 💡 bonus

#29 feat : #28/Check for matching textures
  Makefile
  bonus/cub3d_bonus.h
  bonus/minimap_bonus.c
  bonus/parsing/check_bonus.c
  bonus/parsing/check_map_bonus.c
  bonus/parsing/parse_bonus.c
  mandatory/parsing/check_map.c
Labels: 💻 feat, 🛠 refactor, 💡 bonus

#33 refactor: #31/refactoring parsing part in bonus
  bonus/cub3d_bonus.h
  bonus/ft_func/error_exit_bonus.c
  bonus/ft_func/memory_bonus.c
  bonus/minimap_bonus.c
  bonus/parsing/divide_lst_type_bonus.c
  bonus/parsing/door_sprite_bonus.c
  bonus/parsing/get_image_bonus.c
  bonus/parsing/parse_bonus.c
  bonus/render/screen_bonus.c
  mandatory/cub3d.h
  mandatory/ft_func/error_exit.c
  mandatory/ft_func/memory.c
  mandatory/parsing/get_image.c
  maps/ex.cub
  maps/ex2.cub
  maps/ex3.cub
  maps/ex_bonus.cub
  mlx_opengl/Makefile
  textures/jpg/ea
  textures/jpg/ea.jpg
  textures/jpg/no
  textures/jpg/no.jpg
  textures/jpg/so
  textures/jpg/so.jpg
  textures/jpg/we
  textures/jpg/we.jpg
  textures/png/ea.png
  textures/png/no.png
  textures/png/so.png
  textures/png/we.png
  textures/xpm/ea
  textures/xpm/ea.xpm
  textures/xpm/exit.xpm
  textures/xpm/hero.xpm
  textures/xpm/hero2.xpm
  textures/xpm/no
  textures/xpm/no.xpm
  textures/xpm/so
  textures/xpm/so.xpm
  textures/xpm/we
  textures/xpm/we.xpm
Labels: 🤖 norm, 🛠 refactor, 🐞 fix, ✅ test, 💡 bonus
